// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package player

import (
	"database/sql"
)

type LoginLog struct {
	PlayerID string       `json:"player_id"`
	LoginAt  sql.NullTime `json:"login_at"`
}

type Player struct {
	PlayerID string         `json:"player_id"`
	Email    sql.NullString `json:"email"`
	Name     sql.NullString `json:"name"`
}
