// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package player

import (
	"context"
)

type Querier interface {
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) error
}

var _ Querier = (*Queries)(nil)
