// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package player

import (
	"context"
)

type Querier interface {
	CreateLoginLog(ctx context.Context, playerID string) error
	CreateOrUpdatePlayer(ctx context.Context, arg CreateOrUpdatePlayerParams) error
}

var _ Querier = (*Queries)(nil)
