version: "3.9"

services:
  mariadb:
    image: mariadb:10.10.1-rc
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - app.env
    volumes:
      - mariadb-data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app.env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mariadb

volumes:
  mariadb-data:
