version: "3.9"

services:
  mariadb:
    image: mariadb:10.10.1-rc
    restart: always
    env_file:
      - mariadb.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_SOURCE=root:root_secret@tcp(mariadb:3306)/llg_backend
      - SERVER_PORT
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mariadb
    command:
      - ./wait-for
      - mariadb:3306
      - --
      - ./start.sh
      - ./main

volumes:
  mariadb-data:
