  version: '3'

  tasks:
    server:
      desc: run server
      cmds:
        - go run cmd/app/main.go

    migrateup:
      desc: run migration up
      cmds:
        - migrate -path migrations -database "mysql://root:root_secret@tcp(localhost:3306)/llg_backend" -verbose up

    migratedown:
      desc: run migration down
      cmds:
        - migrate -path migrations -database "mysql://root:root_secret@tcp(localhost:3306)/llg_backend" -verbose down

    sqlc:
      desc: generate code from sql with sqlc
      cmds:
        - sqlc generate