version: '3'

vars:
  POSTGRES_URI: "{{ .POSTGRES_URI }}"

tasks:
  server:
    desc: run server
    cmds:
      - go run cmd/app/main.go

  migrateup:
    desc: run migration up
    cmds:
      - migrate -path migrations -database {{ .POSTGRES_URI }} -verbose up

  migratedown:
    desc: run migration down
    cmds:
      - migrate -path migrations -database {{ .POSTGRES_URI }} -verbose down

  sqlc:
    desc: generate code from sql with sqlc
    cmds:
      - sqlc generate

  wire:
    desc: generate component initialization code with wire
    cmds:
      - wire ./...