version: '3'

vars:
  DB_SOURCE_URI: mysql://{{ .DB_SOURCE }}

tasks:
  server:
    desc: run server
    cmds:
      - go run cmd/app/main.go

  migrateup:
    desc: run migration up
    cmds:
      - migrate -path migrations -database {{ .DB_SOURCE_URI }} -verbose up

  migratedown:
    desc: run migration down
    cmds:
      - migrate -path migrations -database {{ .DB_SOURCE_URI }} -verbose down

  sqlc:
    desc: generate code from sql with sqlc
    cmds:
      - sqlc generate