// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: login_log.sql

package entity

import (
	"context"
)

const createLoginLog = `-- name: CreateLoginLog :exec
INSERT INTO login_log (player_id)
VALUES ($1)
`

func (q *Queries) CreateLoginLog(ctx context.Context, playerID string) error {
	_, err := q.db.ExecContext(ctx, createLoginLog, playerID)
	return err
}
