// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package entity

import (
	"database/sql"
	"time"
)

type LoginLog struct {
	PlayerID string    `json:"player_id"`
	LoginAt  time.Time `json:"login_at"`
}

type Player struct {
	PlayerID string         `json:"player_id"`
	Email    sql.NullString `json:"email"`
	Name     sql.NullString `json:"name"`
}
