// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"llg_backend/internal/controller/http/v1"
	"llg_backend/internal/service"
)

// Injectors from wire.go:

func InitializePlayerController(db *gorm.DB) *v1.PlayerController {
	mapConfigurationService := service.NewMapConfigurationService(db)
	playerStatisticService := service.NewPlayerStatisticService(db)
	playerController := v1.NewPlayerController(mapConfigurationService, playerStatisticService)
	return playerController
}

// wire.go:

var providerSet = wire.NewSet(service.NewPlayerStatisticService, service.NewMapConfigurationService)
