// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package v1

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"llg_backend/internal/service"
)

// Injectors from wire.go:

func InitializePlayerController(db *gorm.DB) *PlayerController {
	mapConfigurationService := service.NewMapConfigurationService(db)
	playerStatisticService := service.NewPlayerStatisticService(db)
	playerService := service.NewPlayerService(db)
	playerController := NewPlayerController(mapConfigurationService, playerStatisticService, playerService)
	return playerController
}

func InitializeAdminController(db *gorm.DB) *AdminController {
	mapConfigurationService := service.NewMapConfigurationService(db)
	playerStatisticService := service.NewPlayerStatisticService(db)
	playerService := service.NewPlayerService(db)
	adminController := NewAdminController(mapConfigurationService, playerStatisticService, playerService)
	return adminController
}

// wire.go:

var providerSet = wire.NewSet(service.NewPlayerStatisticService, service.NewMapConfigurationService, service.NewPlayerService)
