// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: player.sql

package sqlc_generated

import (
	"context"
	"database/sql"
)

const createOrUpdatePlayer = `-- name: CreateOrUpdatePlayer :exec
INSERT INTO player (player_id, email, name)
VALUES ($1, $2, $3)
ON CONFLICT (player_id)
    DO UPDATE SET
    email = $2,
    name = $3
`

type CreateOrUpdatePlayerParams struct {
	PlayerID string         `json:"player_id"`
	Email    sql.NullString `json:"email"`
	Name     sql.NullString `json:"name"`
}

func (q *Queries) CreateOrUpdatePlayer(ctx context.Context, arg CreateOrUpdatePlayerParams) error {
	_, err := q.db.ExecContext(ctx, createOrUpdatePlayer, arg.PlayerID, arg.Email, arg.Name)
	return err
}
